// Refresh supabase/seed/004_markets_snapshot.sql from the live production DB.
//
// Run on demand (e.g. monthly) to keep the local seed close to real shapes
// without depending on a live market-tracker run. The dump only includes
// columns that the schema doesn't compute via triggers — sort_volume and
// tag_slugs are denormalised (migration 057 + 069) and will be filled by
// `markets_set_sort_volume` / `markets_set_tag_slugs` on insert.
//
// Required env:
//   PROD_DATABASE_URL   postgresql://...   read-only role is sufficient.
//
// Usage (from polybet/):
//   PROD_DATABASE_URL=... npm run snapshot:refresh
//
// Output: rewrites supabase/seed/004_markets_snapshot.sql. Commit the diff.

import { writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { Client } from 'pg';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const OUT = path.resolve(__dirname, '..', 'supabase', 'seed', '004_markets_snapshot.sql');

const EVENT_LIMIT = 25; // tune to taste — feed shows ~20 cards per page

const HEADER = `-- AUTO-GENERATED by scripts/refresh-markets-snapshot.ts.
-- Do not edit by hand. Re-run the script to refresh.
-- Source: top ${EVENT_LIMIT} events by volume from production.
-- Denormalised columns (markets.sort_volume, markets.tag_slugs) are
-- omitted — triggers fill them on insert (migrations 057 + 069).

SET session_replication_role = 'replica'; -- skip FK validation during bulk insert
`;

const FOOTER = `\nSET session_replication_role = 'origin';\n`;

function quote(value: unknown): string {
  if (value === null || value === undefined) return 'NULL';
  if (typeof value === 'number') return Number.isFinite(value) ? String(value) : 'NULL';
  if (typeof value === 'boolean') return value ? 'TRUE' : 'FALSE';
  if (value instanceof Date) return `'${value.toISOString()}'`;
  if (Array.isArray(value)) {
    const inner = value.map((v) => String(v).replace(/'/g, "''")).join(',');
    return `'{${inner}}'`;
  }
  return `'${String(value).replace(/'/g, "''")}'`;
}

function toValues(row: Record<string, unknown>, cols: string[]): string {
  return cols.map((c) => quote(row[c])).join(', ');
}

async function main(): Promise<void> {
  const url = process.env.PROD_DATABASE_URL;
  if (!url) {
    console.error('Set PROD_DATABASE_URL to a read-only Postgres URL on the prod DB.');
    process.exit(1);
  }

  const client = new Client({ connectionString: url });
  await client.connect();
  try {
    console.log(`Connected. Pulling top ${EVENT_LIMIT} events by volume...`);

    const eventCols = [
      'id',
      'polymarket_id',
      'slug',
      'title',
      'description',
      'category',
      'image_url',
      'status',
      'close_at',
      'volume',
      'tag_slug',
      'tag_label',
      'tag_slugs',
      'is_visible',
      'created_at',
    ];
    const events = await client.query(
      `SELECT ${eventCols.join(', ')} FROM events
       WHERE status = 'open' AND is_visible = true
       ORDER BY volume DESC NULLS LAST
       LIMIT $1`,
      [EVENT_LIMIT]
    );

    if (events.rows.length === 0) {
      console.warn('No events returned — nothing to write.');
      return;
    }

    const eventIds = events.rows.map((r) => r.id);
    const marketCols = [
      'id',
      'polymarket_id',
      'question',
      'category',
      'status',
      'close_at',
      'event_id',
      'volume',
      'group_label',
      'image_url',
      'created_at',
    ];
    const markets = await client.query(
      `SELECT ${marketCols.join(', ')} FROM markets
       WHERE event_id = ANY($1::uuid[])`,
      [eventIds]
    );

    const marketIds = markets.rows.map((r) => r.id);
    const outcomeCols = ['id', 'market_id', 'name', 'odds', 'effective_odds', 'updated_at'];
    const outcomes = await client.query(
      `SELECT ${outcomeCols.join(', ')} FROM market_outcomes
       WHERE market_id = ANY($1::uuid[])`,
      [marketIds]
    );

    let sql = HEADER;
    sql += `\n-- ${events.rows.length} events\n`;
    sql += `INSERT INTO events (${eventCols.join(', ')}) VALUES\n`;
    sql += events.rows.map((r) => `  (${toValues(r, eventCols)})`).join(',\n');
    sql += '\nON CONFLICT (id) DO NOTHING;\n';

    sql += `\n-- ${markets.rows.length} markets\n`;
    sql += `INSERT INTO markets (${marketCols.join(', ')}) VALUES\n`;
    sql += markets.rows.map((r) => `  (${toValues(r, marketCols)})`).join(',\n');
    sql += '\nON CONFLICT (id) DO NOTHING;\n';

    sql += `\n-- ${outcomes.rows.length} outcomes\n`;
    sql += `INSERT INTO market_outcomes (${outcomeCols.join(', ')}) VALUES\n`;
    sql += outcomes.rows.map((r) => `  (${toValues(r, outcomeCols)})`).join(',\n');
    sql += '\nON CONFLICT (id) DO NOTHING;\n';
    sql += FOOTER;

    await writeFile(OUT, sql, 'utf8');
    console.log(`Wrote ${sql.length} bytes to ${OUT}.`);
    console.log(
      `Events: ${events.rows.length}, markets: ${markets.rows.length}, outcomes: ${outcomes.rows.length}.`
    );
    console.log('\nRun `npx supabase db reset` to apply the new snapshot locally.');
  } finally {
    await client.end();
  }
}

main().catch((err: unknown) => {
  console.error(err);
  process.exit(1);
});
